call ng g @angular-architects/ddd:domain domain1 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain1 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain1 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain1 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain1 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain1 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain1 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain1 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain1 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain1 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain1 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain1 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain1 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain1 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain1 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain1 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain1 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain1 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain1 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain1 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain1 --entity entity20

call ng g @angular-architects/ddd:domain domain2 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain2 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain2 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain2 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain2 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain2 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain2 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain2 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain2 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain2 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain2 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain2 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain2 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain2 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain2 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain2 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain2 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain2 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain2 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain2 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain2 --entity entity20

call ng g @angular-architects/ddd:domain domain3 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain3 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain3 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain3 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain3 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain3 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain3 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain3 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain3 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain3 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain3 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain3 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain3 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain3 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain3 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain3 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain3 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain3 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain3 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain3 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain3 --entity entity20

call ng g @angular-architects/ddd:domain domain4 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain4 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain4 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain4 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain4 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain4 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain4 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain4 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain4 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain4 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain4 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain4 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain4 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain4 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain4 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain4 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain4 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain4 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain4 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain4 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain4 --entity entity20

call ng g @angular-architects/ddd:domain domain5 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain5 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain5 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain5 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain5 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain5 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain5 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain5 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain5 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain5 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain5 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain5 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain5 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain5 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain5 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain5 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain5 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain5 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain5 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain5 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain5 --entity entity20

call ng g @angular-architects/ddd:domain domain6 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain6 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain6 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain6 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain6 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain6 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain6 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain6 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain6 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain6 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain6 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain6 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain6 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain6 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain6 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain6 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain6 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain6 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain6 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain6 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain6 --entity entity20

call ng g @angular-architects/ddd:domain domain7 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain7 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain7 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain7 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain7 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain7 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain7 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain7 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain7 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain7 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain7 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain7 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain7 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain7 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain7 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain7 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain7 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain7 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain7 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain7 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain7 --entity entity20

call ng g @angular-architects/ddd:domain domain8 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain8 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain8 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain8 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain8 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain8 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain8 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain8 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain8 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain8 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain8 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain8 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain8 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain8 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain8 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain8 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain8 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain8 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain8 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain8 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain8 --entity entity20

call ng g @angular-architects/ddd:domain domain9 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain9 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain9 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain9 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain9 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain9 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain9 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain9 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain9 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain9 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain9 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain9 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain9 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain9 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain9 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain9 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain9 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain9 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain9 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain9 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain9 --entity entity20

call ng g @angular-architects/ddd:domain domain10 --add-app
call ng g @angular-architects/ddd:feature feature1 --domain domain10 --entity entity1
call ng g @angular-architects/ddd:feature feature2 --domain domain10 --entity entity2
call ng g @angular-architects/ddd:feature feature3 --domain domain10 --entity entity3
call ng g @angular-architects/ddd:feature feature4 --domain domain10 --entity entity4
call ng g @angular-architects/ddd:feature feature5 --domain domain10 --entity entity5
call ng g @angular-architects/ddd:feature feature6 --domain domain10 --entity entity6
call ng g @angular-architects/ddd:feature feature7 --domain domain10 --entity entity7
call ng g @angular-architects/ddd:feature feature8 --domain domain10 --entity entity8
call ng g @angular-architects/ddd:feature feature9 --domain domain10 --entity entity9
call ng g @angular-architects/ddd:feature feature10 --domain domain10 --entity entity10
call ng g @angular-architects/ddd:feature feature11 --domain domain10 --entity entity11
call ng g @angular-architects/ddd:feature feature12 --domain domain10 --entity entity12
call ng g @angular-architects/ddd:feature feature13 --domain domain10 --entity entity13
call ng g @angular-architects/ddd:feature feature14 --domain domain10 --entity entity14
call ng g @angular-architects/ddd:feature feature15 --domain domain10 --entity entity15
call ng g @angular-architects/ddd:feature feature16 --domain domain10 --entity entity16
call ng g @angular-architects/ddd:feature feature17 --domain domain10 --entity entity17
call ng g @angular-architects/ddd:feature feature18 --domain domain10 --entity entity18
call ng g @angular-architects/ddd:feature feature19 --domain domain10 --entity entity19
call ng g @angular-architects/ddd:feature feature20 --domain domain10 --entity entity20

